// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbK1dj6R7sVXRC2mlKCG_1nHWDsNhpwDA',
    appId: '1:618832922682:web:9043c53d8e02da83650d03',
    messagingSenderId: '618832922682',
    projectId: 'tiktok-tutorial-9baf6',
    authDomain: 'tiktok-tutorial-9baf6.firebaseapp.com',
    storageBucket: 'tiktok-tutorial-9baf6.appspot.com',
    measurementId: 'G-2LW113L05L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAN3cZHZ4OjBBXwFD7o3O83STuFsXZKt1I',
    appId: '1:618832922682:android:7acdc87185832996650d03',
    messagingSenderId: '618832922682',
    projectId: 'tiktok-tutorial-9baf6',
    storageBucket: 'tiktok-tutorial-9baf6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXNzf7OCXbBhUXlqS70j_ReIA1QpQ7_xk',
    appId: '1:618832922682:ios:4ef846ae535d4f07650d03',
    messagingSenderId: '618832922682',
    projectId: 'tiktok-tutorial-9baf6',
    storageBucket: 'tiktok-tutorial-9baf6.appspot.com',
    iosBundleId: 'com.example.tiktokTutorial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXNzf7OCXbBhUXlqS70j_ReIA1QpQ7_xk',
    appId: '1:618832922682:ios:589f83b6b7a407b1650d03',
    messagingSenderId: '618832922682',
    projectId: 'tiktok-tutorial-9baf6',
    storageBucket: 'tiktok-tutorial-9baf6.appspot.com',
    iosBundleId: 'com.example.tiktokTutorial.RunnerTests',
  );
}
